// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TB.Database;

#nullable disable

namespace TB.Database.Migrations
{
    [DbContext(typeof(TBDatabaseContext))]
    partial class TBDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TB.Database.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSupportInteface")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupportNativeLanguage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupportTargetLanguage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "uk",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Ukrainian 🇺🇦"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ru",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Russian 🇷🇺"
                        },
                        new
                        {
                            Id = 3,
                            Code = "en",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "English 🇺🇸"
                        },
                        new
                        {
                            Id = 4,
                            Code = "es",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Spanish 🇪🇸"
                        },
                        new
                        {
                            Id = 5,
                            Code = "fr",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "French 🇫🇷"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ja",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Japanese 🇯🇵"
                        },
                        new
                        {
                            Id = 7,
                            Code = "zh-Hans",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Chinese 🇨🇳"
                        },
                        new
                        {
                            Id = 8,
                            Code = "cs",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Czech 🇨🇿"
                        },
                        new
                        {
                            Id = 9,
                            Code = "da",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Danish 🇩🇰"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hi",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Hindi 🇮🇳"
                        },
                        new
                        {
                            Id = 11,
                            Code = "it",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Italian 🇮🇹"
                        },
                        new
                        {
                            Id = 12,
                            Code = "sv",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Swedish 🇸🇪"
                        },
                        new
                        {
                            Id = 13,
                            Code = "de",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "German 🇩🇪"
                        },
                        new
                        {
                            Id = 14,
                            Code = "pl",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Polish 🇵🇱"
                        },
                        new
                        {
                            Id = 15,
                            Code = "tr",
                            IsSupportInteface = true,
                            IsSupportNativeLanguage = true,
                            IsSupportTargetLanguage = true,
                            Name = "Turkish 🇹🇷"
                        });
                });

            modelBuilder.Entity("TB.Database.Entities.TelegramUser", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("TelegramUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TB.Database.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Translate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 1,
                            Translate = "Мова інтерфейсу:"
                        },
                        new
                        {
                            Id = 2,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 2,
                            Translate = "Язык интерфейса:"
                        },
                        new
                        {
                            Id = 3,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 3,
                            Translate = "Your interface language:"
                        },
                        new
                        {
                            Id = 4,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 4,
                            Translate = "Tu idioma de interfaz:"
                        },
                        new
                        {
                            Id = 5,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 5,
                            Translate = "La langue de votre interface :"
                        },
                        new
                        {
                            Id = 6,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 6,
                            Translate = ""
                        },
                        new
                        {
                            Id = 7,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 7,
                            Translate = ""
                        },
                        new
                        {
                            Id = 8,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 8,
                            Translate = "Váš jazyk rozhraní:"
                        },
                        new
                        {
                            Id = 9,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 9,
                            Translate = "Dit grænsefladesprog:"
                        },
                        new
                        {
                            Id = 10,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 10,
                            Translate = ""
                        },
                        new
                        {
                            Id = 11,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 11,
                            Translate = "La lingua dell'interfaccia:"
                        },
                        new
                        {
                            Id = 12,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 12,
                            Translate = "Ditt gränssnittsspråk:"
                        },
                        new
                        {
                            Id = 13,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 13,
                            Translate = "Ihre Oberflächensprache:"
                        },
                        new
                        {
                            Id = 14,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 14,
                            Translate = "Twój język interfejsu:"
                        },
                        new
                        {
                            Id = 15,
                            Key = "app.languages.interfaceLanguage",
                            LanguageId = 15,
                            Translate = "Arayüz diliniz:"
                        },
                        new
                        {
                            Id = 16,
                            Key = "app.languages.established",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 17,
                            Key = "app.languages.established",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 18,
                            Key = "app.languages.established",
                            LanguageId = 3,
                            Translate = "The languages were established."
                        },
                        new
                        {
                            Id = 19,
                            Key = "app.languages.established",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 20,
                            Key = "app.languages.established",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 21,
                            Key = "app.languages.established",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 22,
                            Key = "app.languages.established",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 23,
                            Key = "app.languages.established",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 24,
                            Key = "app.languages.established",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 25,
                            Key = "app.languages.established",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 26,
                            Key = "app.languages.established",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 27,
                            Key = "app.languages.established",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 28,
                            Key = "app.languages.established",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 29,
                            Key = "app.languages.established",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 30,
                            Key = "app.languages.established",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 31,
                            Key = "app.languages.nativeL",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 32,
                            Key = "app.languages.nativeL",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 33,
                            Key = "app.languages.nativeL",
                            LanguageId = 3,
                            Translate = "Native Language:"
                        },
                        new
                        {
                            Id = 34,
                            Key = "app.languages.nativeL",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 35,
                            Key = "app.languages.nativeL",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 36,
                            Key = "app.languages.nativeL",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 37,
                            Key = "app.languages.nativeL",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 38,
                            Key = "app.languages.nativeL",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 39,
                            Key = "app.languages.nativeL",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 40,
                            Key = "app.languages.nativeL",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 41,
                            Key = "app.languages.nativeL",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 42,
                            Key = "app.languages.nativeL",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 43,
                            Key = "app.languages.nativeL",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 44,
                            Key = "app.languages.nativeL",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 45,
                            Key = "app.languages.nativeL",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 46,
                            Key = "app.languages.targetL",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 47,
                            Key = "app.languages.targetL",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 48,
                            Key = "app.languages.targetL",
                            LanguageId = 3,
                            Translate = "Target Language:"
                        },
                        new
                        {
                            Id = 49,
                            Key = "app.languages.targetL",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 50,
                            Key = "app.languages.targetL",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 51,
                            Key = "app.languages.targetL",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 52,
                            Key = "app.languages.targetL",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 53,
                            Key = "app.languages.targetL",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 54,
                            Key = "app.languages.targetL",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 55,
                            Key = "app.languages.targetL",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 56,
                            Key = "app.languages.targetL",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 57,
                            Key = "app.languages.targetL",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 58,
                            Key = "app.languages.targetL",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 59,
                            Key = "app.languages.targetL",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 60,
                            Key = "app.languages.targetL",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 61,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 62,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 63,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 3,
                            Translate = "Your languages"
                        },
                        new
                        {
                            Id = 64,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 65,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 66,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 67,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 68,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 69,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 70,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 71,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 72,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 73,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 74,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 75,
                            Key = "app.languages.yourLanguages",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 76,
                            Key = "app.languages.canSend",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 77,
                            Key = "app.languages.canSend",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 78,
                            Key = "app.languages.canSend",
                            LanguageId = 3,
                            Translate = "Send text, photo, audio for translating."
                        },
                        new
                        {
                            Id = 79,
                            Key = "app.languages.canSend",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 80,
                            Key = "app.languages.canSend",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 81,
                            Key = "app.languages.canSend",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 82,
                            Key = "app.languages.canSend",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 83,
                            Key = "app.languages.canSend",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 84,
                            Key = "app.languages.canSend",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 85,
                            Key = "app.languages.canSend",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 86,
                            Key = "app.languages.canSend",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 87,
                            Key = "app.languages.canSend",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 88,
                            Key = "app.languages.canSend",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 89,
                            Key = "app.languages.canSend",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 90,
                            Key = "app.languages.canSend",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 91,
                            Key = "app.images.text",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 92,
                            Key = "app.images.text",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 93,
                            Key = "app.images.text",
                            LanguageId = 3,
                            Translate = "<b>Text on photo</b>"
                        },
                        new
                        {
                            Id = 94,
                            Key = "app.images.text",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 95,
                            Key = "app.images.text",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 96,
                            Key = "app.images.text",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 97,
                            Key = "app.images.text",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 98,
                            Key = "app.images.text",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 99,
                            Key = "app.images.text",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 100,
                            Key = "app.images.text",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 101,
                            Key = "app.images.text",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 102,
                            Key = "app.images.text",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 103,
                            Key = "app.images.text",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 104,
                            Key = "app.images.text",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 105,
                            Key = "app.images.text",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 106,
                            Key = "app.images.objects",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 107,
                            Key = "app.images.objects",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 108,
                            Key = "app.images.objects",
                            LanguageId = 3,
                            Translate = "<b>Image objects</b>"
                        },
                        new
                        {
                            Id = 109,
                            Key = "app.images.objects",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 110,
                            Key = "app.images.objects",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 111,
                            Key = "app.images.objects",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 112,
                            Key = "app.images.objects",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 113,
                            Key = "app.images.objects",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 114,
                            Key = "app.images.objects",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 115,
                            Key = "app.images.objects",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 116,
                            Key = "app.images.objects",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 117,
                            Key = "app.images.objects",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 118,
                            Key = "app.images.objects",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 119,
                            Key = "app.images.objects",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 120,
                            Key = "app.images.objects",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 121,
                            Key = "app.images.description",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 122,
                            Key = "app.images.description",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 123,
                            Key = "app.images.description",
                            LanguageId = 3,
                            Translate = "<b>Image description</b>"
                        },
                        new
                        {
                            Id = 124,
                            Key = "app.images.description",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 125,
                            Key = "app.images.description",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 126,
                            Key = "app.images.description",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 127,
                            Key = "app.images.description",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 128,
                            Key = "app.images.description",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 129,
                            Key = "app.images.description",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 130,
                            Key = "app.images.description",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 131,
                            Key = "app.images.description",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 132,
                            Key = "app.images.description",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 133,
                            Key = "app.images.description",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 134,
                            Key = "app.images.description",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 135,
                            Key = "app.images.description",
                            LanguageId = 15,
                            Translate = ""
                        },
                        new
                        {
                            Id = 136,
                            Key = "app.texts.maybeMean",
                            LanguageId = 1,
                            Translate = ""
                        },
                        new
                        {
                            Id = 137,
                            Key = "app.texts.maybeMean",
                            LanguageId = 2,
                            Translate = ""
                        },
                        new
                        {
                            Id = 138,
                            Key = "app.texts.maybeMean",
                            LanguageId = 3,
                            Translate = "<b>Maybe you mean</b>"
                        },
                        new
                        {
                            Id = 139,
                            Key = "app.texts.maybeMean",
                            LanguageId = 4,
                            Translate = ""
                        },
                        new
                        {
                            Id = 140,
                            Key = "app.texts.maybeMean",
                            LanguageId = 5,
                            Translate = ""
                        },
                        new
                        {
                            Id = 141,
                            Key = "app.texts.maybeMean",
                            LanguageId = 6,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 142,
                            Key = "app.texts.maybeMean",
                            LanguageId = 7,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 143,
                            Key = "app.texts.maybeMean",
                            LanguageId = 8,
                            Translate = ""
                        },
                        new
                        {
                            Id = 144,
                            Key = "app.texts.maybeMean",
                            LanguageId = 9,
                            Translate = ""
                        },
                        new
                        {
                            Id = 145,
                            Key = "app.texts.maybeMean",
                            LanguageId = 10,
                            Translate = "1"
                        },
                        new
                        {
                            Id = 146,
                            Key = "app.texts.maybeMean",
                            LanguageId = 11,
                            Translate = ""
                        },
                        new
                        {
                            Id = 147,
                            Key = "app.texts.maybeMean",
                            LanguageId = 12,
                            Translate = ""
                        },
                        new
                        {
                            Id = 148,
                            Key = "app.texts.maybeMean",
                            LanguageId = 13,
                            Translate = ""
                        },
                        new
                        {
                            Id = 149,
                            Key = "app.texts.maybeMean",
                            LanguageId = 14,
                            Translate = ""
                        },
                        new
                        {
                            Id = 150,
                            Key = "app.texts.maybeMean",
                            LanguageId = 15,
                            Translate = ""
                        });
                });

            modelBuilder.Entity("TB.Database.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InterfaceLanguageId")
                        .HasColumnType("integer");

                    b.Property<int?>("NativeLanguageId")
                        .HasColumnType("integer");

                    b.Property<bool>("RecognizeEnglishMeaning")
                        .HasColumnType("boolean");

                    b.Property<int?>("TargetLanguageId")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceLanguageId");

                    b.HasIndex("NativeLanguageId");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("TB.Database.Entities.Translation", b =>
                {
                    b.HasOne("TB.Database.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("TB.Database.Entities.UserSettings", b =>
                {
                    b.HasOne("TB.Database.Entities.Language", "InterfaceLanguage")
                        .WithMany("UserSettingsInterfaceLangs")
                        .HasForeignKey("InterfaceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TB.Database.Entities.Language", "NativeLanguage")
                        .WithMany("UserSettingsNativeLangs")
                        .HasForeignKey("NativeLanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TB.Database.Entities.Language", "TargetLanguage")
                        .WithMany("UserSettingsTargetLangs")
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TB.Database.Entities.TelegramUser", "TelegramUser")
                        .WithOne("UserSettings")
                        .HasForeignKey("TB.Database.Entities.UserSettings", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterfaceLanguage");

                    b.Navigation("NativeLanguage");

                    b.Navigation("TargetLanguage");

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("TB.Database.Entities.Language", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("UserSettingsInterfaceLangs");

                    b.Navigation("UserSettingsNativeLangs");

                    b.Navigation("UserSettingsTargetLangs");
                });

            modelBuilder.Entity("TB.Database.Entities.TelegramUser", b =>
                {
                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
