name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  migrate:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v3
      - name: Update database
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update -c TBDatabaseContext -p EnglishWordsRecognizer/EnglishWordsRecognizer -s EnglishWordsRecognizer/EnglishWordsRecognizer
        env:
          ASPNETCORE_ENVIRONMENT: Production
          Database: ${{ secrets.DATABASECONNECTION }}
